# Makefile Proyecto de Programacion II
# Oswaldo Capriles
# Victor Tortolero

# Variables
CC = g++
NAME = primos

# Instrucciones
all:
	$(CC) $(NAME).cpp -o $(NAME)
run:
	./$(NAME) < entrada.in
clean:
	rm -rf $(NAME) *.o