# Makefile Proyecto de Programacion II
# Oswaldo Capriles
# Victor Tortolero

# Variables
CC = g++
NAME = primos
FLAGS = -Wall -Wextra

# Instrucciones
all:
	$(CC) $(NAME).cpp -o $(NAME) $(FLAGS)
run:
	./$(NAME) < entrada.in
clean:
	rm -rf $(NAME) *.o